### ISSUE TITLE
Compatible with KiCad 8?

### ISSUE THREAD

**Issue by boromyr** [sparkfun/SparkFun_KiCad_Panelizer#9]

**Comment by PaulZC** [comment]
Hi @boromyr ,

The Panelizer _should_ be compatible with KiCad 8. But, right now, it will not work, because:

* We check for KiCad 7 [here](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/blob/f611e730d833aa8305e26883a42c7324026dcc55/SparkFunKiCadPanelizer/plugin.py#L97)
* There is at least one [KiCad 7 dependency](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/blob/f611e730d833aa8305e26883a42c7324026dcc55/SparkFunKiCadPanelizer/panelizer/panelizer.py#L960) we need to fix
* And we need to fix the [version](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/blob/f611e730d833aa8305e26883a42c7324026dcc55/pcm/metadata_template.json#L32) in the JSON

There may be other things that need to change too. I have not tried KiCad 8 yet...

I will leave this open until we have time to update it for KiCad 8.

Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi @boromyr ,

v1.2.0 is compatible with both KiCad 7 and 8.

v1.2.0 is available now on the [Releases page](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/releases) - you can download the zip file and install it manually. It will be available automatically through the PCM when the KiCad team have time to [merge it](https://gitlab.com/kicad/addons/metadata/-/merge_requests/318).

Best wishes,
Paul
